name = "Craftoria"
author = "TeamAOE"
version = "1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af1a9167b53bdde5d2f50436c919524e46efa89a69df51c6942977cd0371164b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
