name = "Craftoria"
author = "TeamAOE"
version = "1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "410529a3f51cad14d6f3526229e2439a4a5b5ac219afb40609dccf033a36682f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
