name = "Craftoria"
author = "TeamAOE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c50c7ff6fd4d311e9a8915a77e5f47a0b6a83289b720972b7af76a89ef74e59b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
