name = "Craftoria"
author = "TeamAOE"
version = "1.21.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "181a47789cb430ed3e05bff7aeda7516f2154345b6ef8243409b4b007cc0dd6a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
