name = "Craftoria"
author = "TeamAOE"
version = "1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de478040d0e91251e2312036e657f7868143f92bc7cb786ab29e91f01d19e165"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
