name = "Craftoria"
author = "TeamAOE"
version = "1.22.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21832007ee92e481779401d67e3bcfdd458203a78ca961b4d2451dc84e159d3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
