name = "Craftoria"
author = "TeamAOE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbd45e63b934f5c461ad5ec1e1b1a16eae0900a9054d1511fe7526ecfdefa6ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
