name = "Craftoria"
author = "TeamAOE"
version = "1.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ce6ce8517c53af2b5e6ef21510ca2b6cd48442ad584f5bb404a7a558235a618"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
